### ISSUE TITLE
HashCheckAsync autostart after complete not change seeding or downloading

### ISSUE THREAD

**Issue by longxoay1** [mono/monotorrent#155]
Hi alanmcgovern!
HashCheckAsync autostart after complete not change seeding or downloading. 
You check, please!

**Comment by alanmcgovern** [comment]
Hrmm, the method looks correctly implemented. Can you let me know which version, or git hash, of the library you're using?

**Comment by alanmcgovern** [comment]
You were right. Fixed now!

**Comment by catholic** [comment]
The issue seems to be not fixed.
After State.Hashing TorrentManager always gets State.Stopped, not Downloading or Seeding

**Comment by alanmcgovern** [comment]
So all you're doing is creating a torrent, then calling `StartAsync`, and the state never moves to `Seeding` or `Downloading`? In this scenario you are *not* calling `HashCheckAsync` ?

**Comment by catholic** [comment]
Yes, I'm not using HashCheckAsync is this scenario.

I solved the problem. It was on my side. Some changes in MonoTorrent impacted on behavior in my app.

Thank you for your job!

**Comment by alanmcgovern** [comment]
Phew! :)

If you think a change in monotorrent is breaking something in your app, and it really *shouldn't* break your app, let me know what the change was so I can review it.
